### PR TITLE
added checkout page

### PR DESCRIPTION
**Pull request by Rohanmond**
Screenshot 2022-02-22 at 6 21 26 PM

file structure => pages=> auth=> checkout.html

### CODE REVIEW

**Review by anuj-kumary — APPROVED** [review]
Looks Good To Me!!

**Review by hrishi82 — APPROVED** [review]
The code looks okay! Can merge!

Visual suggestion: Try to center the content to give it a more even look!

**Review by MurtazaBagwala07 — APPROVED** [review]
Looks good to merge

**Review by PeeyushPrashant — APPROVED** [review]
looks great

**Pull request merged**
