### PR TITLE
added forget password page

### PR DESCRIPTION
**Pull request by Rohanmond**
Screenshot 2022-02-22 at 4 03 26 PM

file structure => pages=> authentication=> forgetpassword.html

### CODE REVIEW

**Review by vinc3nati — APPROVED** [review]
Clean

**Review by Aman-Jain1996 — APPROVED** [review]
Suggestion - Change 1st button name to Reset Passoword ann login again to login only

**Comment by Rohanmond** [comment]
> Suggestion - Change 1st button name to Reset Passoword ann login again to login only

thanks..it is fixed now

**Comment by Shah-Arsalan** [comment]
Not sure why two buttons are there ... else everything looks  good

**Review by Shah-Arsalan — APPROVED** [review]

**Pull request merged**
