### PR TITLE
Feat: added  auth

### PR DESCRIPTION
**Pull request by Rohanmond**
Screenshot 2022-02-11 at 12 20 56 PM
Screenshot 2022-02-11 at 12 21 02 PM

Added Signup login page
file location=> pages=> authentication => signup.html, login.html

### CODE REVIEW

**Review by anuj-kumary — COMMENTED** [review]
One suggestion is don't give multiple colors try to stick with one or two in your login and signup there is so many different colors you used

**Comment by Shah-Arsalan** [comment]
Need not give multiple colors . Fix it

**Review by Aman-Jain1996 — APPROVED** [review]
Looks good to merge

**Comment by Rohanmond** [comment]
> Need not give multiple colors . Fix it

It is fixed now.Thanks

**Comment by Rohanmond** [comment]
> One suggestion is don't give multiple colors try to stick with one or two in your login and signup there is so many different colors you used

It is fixed now .Thanks

**Review by Shah-Arsalan — APPROVED** [review]

**Pull request merged**
